export enum FlowCommandId {
  COPY = 'flow.copy',
  CUT = 'flow.cut',
  PASTE = 'flow.paste',
  SELECT_ALL = 'flow.select-all',
  CANCEL_SELECT = 'flow.cancel-select',
  GROUP = 'flow.group',
  UNGROUP = 'flow.ungroup',
  COLLAPSE = 'flow.collapse',
  EXPAND = 'flow.expand',
  DELETE = 'flow.delete',
  UNDO = 'flow.undo',
  REDO = 'flow.redo',
  RESET_ZOOM = 'flow.reset-zoom',
  ZOOM_IN = 'flow.zoom-in',
  ZOOM_OUT = 'flow.zoom-out',
  PREVIEW_MODE = 'flow.preview-mode',
}
